spring:
  application:
    name: customer-service

  # MongoDB Atlas Connection
  data:
    mongodb:
      uri: mongodb+srv://abhiumap31:RilGQicKUHIhUWuP@cluster0.2lirn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: customer-service

  # Hibernate and JPA properties (if applicable)
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MongoDialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka Server
    fetch-registry: true # Fetch the registry from Eureka Server
    register-with-eureka: true # Enable registration with Eureka Server
  instance:
    prefer-ip-address: true # Prefer using IP address for registration
    instance-id: ${spring.application.name}:${server.port} # Unique instance ID for each service

